FROM meis/perl5
RUN apt-get update && apt-get install -y libperl-dev libmagickcore-6.q16-dev

RUN ln -s /usr/include/x86_64-linux-gnu/ImageMagick-6/magick/magick-baseconfig.h /usr/include/ImageMagick-6/magick/
